version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    command: npm run dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3001/api
